name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: 'main'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pip tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Update dependencies
        run: poetry update

      - name: Run unit tests
        run: poetry run test

      - name: Publish package to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build

      - name: Clean up
        if: always()
        run: rm -rf dist
